# This docker is for benchmarking gnn project
# Create a docker based on ubuntu 18.04, including conda and other python environment for CPU.
FROM ubuntu:16.04

# System packages 
RUN apt-get update && apt-get install -y curl

# Install miniconda to /miniconda
RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda -b \
    && rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH=/miniconda/bin:${PATH}

RUN conda update -y conda

# Install CUDA 10.0 on Ubuntu 16.04
RUN apt-get --purge remove "*cublas*" "cuda*" \
    && apt --purge remove "nvidia*" \
    && apt autoremove \
    && apt-get install wget \
    && wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb\
    && dpkg -i cuda-repo-ubuntu1604_10.0.130-1_amd64.deb \
    && apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub \
    && apt update \
    && apt install -y cuda-10-0



